Add loast logo
department-of-veterans-affairs/lighthouse-oas-tests pull request #27
Opened 2021-03-31 17:28 UTC by ediiotero

Story: [API-5552](https://vajira.max.gov/browse/API-5552)

Add loast logo to read me

2021-03-31 18:36 UTC, alexandervalencia submitted a review, later dismissed
Not sure that we want to commit the package-lock.json as part of this commit...

Aside from that LGTM! 🍞

2021-03-31 19:08 UTC, RockslideJr requested changes

2021-03-31 19:08 UTC, RockslideJr commented on README.md
> +</p>
Can we convert this to markdown?
Looks like
```md
![Logo](images/loast-logo.png)

# LOAST
```
should work

2021-03-31 19:09 UTC, RockslideJr commented on README.md
> +</p>
oh wait that would cancel out the centering. NVM me

2021-03-31 19:09 UTC, RockslideJr approved these changes

2021-03-31 19:11 UTC, RockslideJr requested changes

2021-03-31 19:11 UTC, RockslideJr commented on README.md
> +</p>
nothing else is centered though, so i'm back to thinking we should just go with markdown

2021-03-31 21:46 UTC, RockslideJr requested changes
The readme changes look good. For some reason the PR is trying to delete the package-lock, which we probably don't want to do. The updates you saw before might be due to a node or npm version mismatch. What versions are you on?

2021-04-01 15:42 UTC, RockslideJr approved these changes

2021-04-01 17:24 UTC, merged